Ext.define('vyl.view.ventas.cierre.FormularioViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.ventasciere',

    stores: {
        stNacionalidad: {
            fields: ['COD', 'NACIONALIDAD'],
            
            data: [
                {COD: 'chile',           NACIONALIDAD: 'Chile'},
                {COD: 'argentina',       NACIONALIDAD: 'Argentina'},
                {COD: 'bolivia',         NACIONALIDAD: 'Bolivia'},
                {COD: 'brasil',          NACIONALIDAD: 'Brasil'},
                {COD: 'colombia',        NACIONALIDAD: 'Colombia'},
                {COD: 'ecuador',         NACIONALIDAD: 'Ecuador'},
                {COD: 'paraguay',        NACIONALIDAD: 'Paraguay'},
                {COD: 'peru',            NACIONALIDAD: 'Perú'},
                {COD: 'uruguay',         NACIONALIDAD: 'Uruguay'},
                {COD: 'venezuela',       NACIONALIDAD: 'Venezuela'},
                {COD: '-',               NACIONALIDAD: '_______________'},
                {COD: 'afganistán' ,NACIONALIDAD: 'Afganistán'},
                {COD: 'albania' ,NACIONALIDAD: 'Albania'},
                {COD: 'alemania' ,NACIONALIDAD: 'Alemania'},
                {COD: 'andorra' ,NACIONALIDAD: 'Andorra'},
                {COD: 'angola' ,NACIONALIDAD: 'Angola'},
                {COD: 'antigua y barbuda' ,NACIONALIDAD: 'Antigua y Barbuda'},
                {COD: 'arabia saudita' ,NACIONALIDAD: 'Arabia Saudita'},
                {COD: 'argelia' ,NACIONALIDAD: 'Argelia'},
                {COD: 'armenia' ,NACIONALIDAD: 'Armenia'},
                {COD: 'australia' ,NACIONALIDAD: 'Australia'},
                {COD: 'austria' ,NACIONALIDAD: 'Austria'},
                {COD: 'azerbaiyán' ,NACIONALIDAD: 'Azerbaiyán'},
                {COD: 'bahamas' ,NACIONALIDAD: 'Bahamas'},
                {COD: 'bangladés' ,NACIONALIDAD: 'Bangladés'},
                {COD: 'barbados' ,NACIONALIDAD: 'Barbados'},
                {COD: 'baréin' ,NACIONALIDAD: 'Baréin'},
                {COD: 'bélgica' ,NACIONALIDAD: 'Bélgica'},
                {COD: 'belice' ,NACIONALIDAD: 'Belice'},
                {COD: 'benín' ,NACIONALIDAD: 'Benín'},
                {COD: 'bielorrusia' ,NACIONALIDAD: 'Bielorrusia'},
                {COD: 'birmania' ,NACIONALIDAD: 'Birmania'},
                {COD: 'bosnia y herzegovina' ,NACIONALIDAD: 'Bosnia y Herzegovina'},
                {COD: 'botsuana' ,NACIONALIDAD: 'Botsuana'},
                {COD: 'brunéi' ,NACIONALIDAD: 'Brunéi'},
                {COD: 'bulgaria' ,NACIONALIDAD: 'Bulgaria'},
                {COD: 'burkina faso' ,NACIONALIDAD: 'Burkina Faso'},
                {COD: 'burundi' ,NACIONALIDAD: 'Burundi'},
                {COD: 'bután' ,NACIONALIDAD: 'Bután'},
                {COD: 'cabo verde' ,NACIONALIDAD: 'Cabo Verde'},
                {COD: 'camboya' ,NACIONALIDAD: 'Camboya'},
                {COD: 'camerún' ,NACIONALIDAD: 'Camerún'},
                {COD: 'canadá' ,NACIONALIDAD: 'Canadá'},
                {COD: 'catar' ,NACIONALIDAD: 'Catar'},
                {COD: 'chad' ,NACIONALIDAD: 'Chad'},
                {COD: 'china' ,NACIONALIDAD: 'China'},
                {COD: 'chipre' ,NACIONALIDAD: 'Chipre'},
                {COD: 'ciudad del vaticano' ,NACIONALIDAD: 'Ciudad del Vaticano'},
                {COD: 'comoras' ,NACIONALIDAD: 'Comoras'},
                {COD: 'corea del norte' ,NACIONALIDAD: 'Corea del Norte'},
                {COD: 'corea del sur' ,NACIONALIDAD: 'Corea del Sur'},
                {COD: 'costa de marfil' ,NACIONALIDAD: 'Costa de Marfil'},
                {COD: 'costa rica' ,NACIONALIDAD: 'Costa Rica'},
                {COD: 'croacia' ,NACIONALIDAD: 'Croacia'},
                {COD: 'cuba' ,NACIONALIDAD: 'Cuba'},
                {COD: 'dinamarca' ,NACIONALIDAD: 'Dinamarca'},
                {COD: 'dominica' ,NACIONALIDAD: 'Dominica'},
                {COD: 'egipto' ,NACIONALIDAD: 'Egipto'},
                {COD: 'el salvador' ,NACIONALIDAD: 'El Salvador'},
                {COD: 'eau' ,NACIONALIDAD: 'Emiratos Árabes Unidos'},
                {COD: 'eritrea' ,NACIONALIDAD: 'Eritrea'},
                {COD: 'eslovaquia' ,NACIONALIDAD: 'Eslovaquia'},
                {COD: 'eslovenia' ,NACIONALIDAD: 'Eslovenia'},
                {COD: 'españa' ,NACIONALIDAD: 'España'},
                {COD: 'estados unidos' ,NACIONALIDAD: 'Estados Unidos'},
                {COD: 'estonia' ,NACIONALIDAD: 'Estonia'},
                {COD: 'etiopía' ,NACIONALIDAD: 'Etiopía'},
                {COD: 'filipinas' ,NACIONALIDAD: 'Filipinas'},
                {COD: 'finlandia' ,NACIONALIDAD: 'Finlandia'},
                {COD: 'fiyi' ,NACIONALIDAD: 'Fiyi'},
                {COD: 'francia' ,NACIONALIDAD: 'Francia'},
                {COD: 'gabón' ,NACIONALIDAD: 'Gabón'},
                {COD: 'gambia' ,NACIONALIDAD: 'Gambia'},
                {COD: 'georgia' ,NACIONALIDAD: 'Georgia'},
                {COD: 'ghana' ,NACIONALIDAD: 'Ghana'},
                {COD: 'granada' ,NACIONALIDAD: 'Granada'},
                {COD: 'grecia' ,NACIONALIDAD: 'Grecia'},
                {COD: 'guatemala' ,NACIONALIDAD: 'Guatemala'},
                {COD: 'guyana' ,NACIONALIDAD: 'Guyana'},
                {COD: 'guinea' ,NACIONALIDAD: 'Guinea'},
                {COD: 'guinea ecuatorial' ,NACIONALIDAD: 'Guinea ecuatorial'},
                {COD: 'guinea-bisáu' ,NACIONALIDAD: 'Guinea-Bisáu'},
                {COD: 'haití' ,NACIONALIDAD: 'Haití'},
                {COD: 'honduras' ,NACIONALIDAD: 'Honduras'},
                {COD: 'hungría' ,NACIONALIDAD: 'Hungría'},
                {COD: 'india' ,NACIONALIDAD: 'India'},
                {COD: 'indonesia' ,NACIONALIDAD: 'Indonesia'},
                {COD: 'irak' ,NACIONALIDAD: 'Irak'},
                {COD: 'irán' ,NACIONALIDAD: 'Irán'},
                {COD: 'irlanda' ,NACIONALIDAD: 'Irlanda'},
                {COD: 'islandia' ,NACIONALIDAD: 'Islandia'},
                {COD: 'islas marshall' ,NACIONALIDAD: 'Islas Marshall'},
                {COD: 'islas salomón' ,NACIONALIDAD: 'Islas Salomón'},
                {COD: 'israel' ,NACIONALIDAD: 'Israel'},
                {COD: 'italia' ,NACIONALIDAD: 'Italia'},
                {COD: 'jamaica' ,NACIONALIDAD: 'Jamaica'},
                {COD: 'japón' ,NACIONALIDAD: 'Japón'},
                {COD: 'jordania' ,NACIONALIDAD: 'Jordania'},
                {COD: 'kazajistán' ,NACIONALIDAD: 'Kazajistán'},
                {COD: 'kenia' ,NACIONALIDAD: 'Kenia'},
                {COD: 'kirguistán' ,NACIONALIDAD: 'Kirguistán'},
                {COD: 'kiribati' ,NACIONALIDAD: 'Kiribati'},
                {COD: 'kuwait' ,NACIONALIDAD: 'Kuwait'},
                {COD: 'laos' ,NACIONALIDAD: 'Laos'},
                {COD: 'lesoto' ,NACIONALIDAD: 'Lesoto'},
                {COD: 'letonia' ,NACIONALIDAD: 'Letonia'},
                {COD: 'líbano' ,NACIONALIDAD: 'Líbano'},
                {COD: 'liberia' ,NACIONALIDAD: 'Liberia'},
                {COD: 'libia' ,NACIONALIDAD: 'Libia'},
                {COD: 'liechtenstein' ,NACIONALIDAD: 'Liechtenstein'},
                {COD: 'lituania' ,NACIONALIDAD: 'Lituania'},
                {COD: 'luxemburgo' ,NACIONALIDAD: 'Luxemburgo'},
                {COD: 'madagascar' ,NACIONALIDAD: 'Madagascar'},
                {COD: 'malasia' ,NACIONALIDAD: 'Malasia'},
                {COD: 'malaui' ,NACIONALIDAD: 'Malaui'},
                {COD: 'maldivas' ,NACIONALIDAD: 'Maldivas'},
                {COD: 'malí' ,NACIONALIDAD: 'Malí'},
                {COD: 'malta' ,NACIONALIDAD: 'Malta'},
                {COD: 'marruecos' ,NACIONALIDAD: 'Marruecos'},
                {COD: 'mauricio' ,NACIONALIDAD: 'Mauricio'},
                {COD: 'mauritania' ,NACIONALIDAD: 'Mauritania'},
                {COD: 'méxico' ,NACIONALIDAD: 'México'},
                {COD: 'micronesia' ,NACIONALIDAD: 'Micronesia'},
                {COD: 'moldavia' ,NACIONALIDAD: 'Moldavia'},
                {COD: 'mónaco' ,NACIONALIDAD: 'Mónaco'},
                {COD: 'mongolia' ,NACIONALIDAD: 'Mongolia'},
                {COD: 'montenegro' ,NACIONALIDAD: 'Montenegro'},
                {COD: 'mozambique' ,NACIONALIDAD: 'Mozambique'},
                {COD: 'namibia' ,NACIONALIDAD: 'Namibia'},
                {COD: 'nauru' ,NACIONALIDAD: 'Nauru'},
                {COD: 'nepal' ,NACIONALIDAD: 'Nepal'},
                {COD: 'nicaragua' ,NACIONALIDAD: 'Nicaragua'},
                {COD: 'níger' ,NACIONALIDAD: 'Níger'},
                {COD: 'nigeria' ,NACIONALIDAD: 'Nigeria'},
                {COD: 'noruega' ,NACIONALIDAD: 'Noruega'},
                {COD: 'nueva zelanda' ,NACIONALIDAD: 'Nueva Zelanda'},
                {COD: 'omán' ,NACIONALIDAD: 'Omán'},
                {COD: 'países bajos' ,NACIONALIDAD: 'Países Bajos'},
                {COD: 'pakistán' ,NACIONALIDAD: 'Pakistán'},
                {COD: 'palaos' ,NACIONALIDAD: 'Palaos'},
                {COD: 'panamá' ,NACIONALIDAD: 'Panamá'},
                {COD: 'papúa nueva guinea' ,NACIONALIDAD: 'Papúa Nueva Guinea'},
                {COD: 'polonia' ,NACIONALIDAD: 'Polonia'},
                {COD: 'portugal' ,NACIONALIDAD: 'Portugal'},
                {COD: 'reino unido' ,NACIONALIDAD: 'Reino Unido'},
                {COD: 'república centroafricana' ,NACIONALIDAD: 'República Centroafricana'},
                {COD: 'república checa' ,NACIONALIDAD: 'República Checa'},
                {COD: 'república de macedonia' ,NACIONALIDAD: 'República de Macedonia'},
                {COD: 'república del congo' ,NACIONALIDAD: 'República del Congo'},
                {COD: 'república democrática del congo' ,NACIONALIDAD: 'República Democrática del Congo'},
                {COD: 'república dominicana' ,NACIONALIDAD: 'República Dominicana'},
                {COD: 'república sudafricana' ,NACIONALIDAD: 'República Sudafricana'},
                {COD: 'ruanda' ,NACIONALIDAD: 'Ruanda'},
                {COD: 'rumanía' ,NACIONALIDAD: 'Rumanía'},
                {COD: 'rusia' ,NACIONALIDAD: 'Rusia'},
                {COD: 'samoa' ,NACIONALIDAD: 'Samoa'},
                {COD: 'san cristóbal y nieves' ,NACIONALIDAD: 'San Cristóbal y Nieves'},
                {COD: 'san marino' ,NACIONALIDAD: 'San Marino'},
                {COD: 'san vicente y las granadinas' ,NACIONALIDAD: 'San Vicente y las Granadinas'},
                {COD: 'santa lucía' ,NACIONALIDAD: 'Santa Lucía'},
                {COD: 'santo tomé y príncipe' ,NACIONALIDAD: 'Santo Tomé y Príncipe'},
                {COD: 'senegal' ,NACIONALIDAD: 'Senegal'},
                {COD: 'serbia' ,NACIONALIDAD: 'Serbia'},
                {COD: 'seychelles' ,NACIONALIDAD: 'Seychelles'},
                {COD: 'sierra leona' ,NACIONALIDAD: 'Sierra Leona'},
                {COD: 'singapur' ,NACIONALIDAD: 'Singapur'},
                {COD: 'siria' ,NACIONALIDAD: 'Siria'},
                {COD: 'somalia' ,NACIONALIDAD: 'Somalia'},
                {COD: 'sri lanka' ,NACIONALIDAD: 'Sri Lanka'},
                {COD: 'suazilandia' ,NACIONALIDAD: 'Suazilandia'},
                {COD: 'sudán' ,NACIONALIDAD: 'Sudán'},
                {COD: 'sudán del sur' ,NACIONALIDAD: 'Sudán del Sur'},
                {COD: 'suecia' ,NACIONALIDAD: 'Suecia'},
                {COD: 'suiza' ,NACIONALIDAD: 'Suiza'},
                {COD: 'surinam' ,NACIONALIDAD: 'Surinam'},
                {COD: 'tailandia' ,NACIONALIDAD: 'Tailandia'},
                {COD: 'tanzania' ,NACIONALIDAD: 'Tanzania'},
                {COD: 'tayikistán' ,NACIONALIDAD: 'Tayikistán'},
                {COD: 'timor oriental' ,NACIONALIDAD: 'Timor Oriental'},
                {COD: 'togo' ,NACIONALIDAD: 'Togo'},
                {COD: 'tonga' ,NACIONALIDAD: 'Tonga'},
                {COD: 'trinidad y tobago' ,NACIONALIDAD: 'Trinidad y Tobago'},
                {COD: 'túnez' ,NACIONALIDAD: 'Túnez'},
                {COD: 'turkmenistán' ,NACIONALIDAD: 'Turkmenistán'},
                {COD: 'turquía' ,NACIONALIDAD: 'Turquía'},
                {COD: 'tuvalu' ,NACIONALIDAD: 'Tuvalu'},
                {COD: 'ucrania' ,NACIONALIDAD: 'Ucrania'},
                {COD: 'uganda' ,NACIONALIDAD: 'Uganda'},
                {COD: 'uzbekistán' ,NACIONALIDAD: 'Uzbekistán'},
                {COD: 'vanuatu' ,NACIONALIDAD: 'Vanuatu'},
                {COD: 'vietnam' ,NACIONALIDAD: 'Vietnam'},
                {COD: 'yemen' ,NACIONALIDAD: 'Yemen'},
                {COD: 'yibuti' ,NACIONALIDAD: 'Yibuti'},
                {COD: 'zambia' ,NACIONALIDAD: 'Zambia'},
                {COD: 'zimbabue' ,NACIONALIDAD: 'Zimbabue'},
            ]
        },
        
        stVendedores: {

        }
    }
});